# Generated by Django 4.0.4 on 2022-04-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='create',
            field=models.IntegerField(default=2010),
        ),
    ]
