# Generated by Django 4.0.4 on 2022-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_options_alter_car_content_alter_car_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='compony',
            field=models.TextField(null=True, verbose_name='компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='year_budjet',
            field=models.IntegerField(null=True, verbose_name='годовой доход'),
        ),
    ]
