# Generated by Django 4.0.4 on 2022-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_compony_car_year_budjet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony', models.TextField(null=True, verbose_name='компания')),
                ('year_budjet', models.IntegerField(null=True, verbose_name='годовой доход')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='compony',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year_budjet',
        ),
    ]
