# Generated by Django 4.0.4 on 2022-04-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_company_remove_car_compony_remove_car_year_budjet'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.company'),
        ),
    ]
