# Generated by Django 4.0.4 on 2022-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40, verbose_name='компания поставщик')),
                ('type_detail', models.TextField(verbose_name='тип деталей')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='provider',
            field=models.ManyToManyField(to='cars.provider'),
        ),
    ]
