# Generated by Django 4.0.4 on 2022-04-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_provider_car_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.director'),
        ),
    ]
