# Generated by Django 4.0.4 on 2022-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_director_company_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='provider',
            field=models.ManyToManyField(null=True, to='cars.provider'),
        ),
    ]
