# Generated by Django 4.0.4 on 2022-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='provider',
            field=models.ManyToManyField(to='cars.provider'),
        ),
    ]
